version: '3.8'

services:
  postgres_db:
    image: bitnami/postgresql:16.3.0
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    ports:
      - "3000:3000"
    depends_on:
      - postgres_db
    environment:
      DATABASE_URL: ${DATABASE_URL}

volumes:
  postgres_data:
