version: '3.8'

services:
  postgres_db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example_password
      POSTGRES_DB: example_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    ports:
      - "3000:3000"
    depends_on:
      - postgres_db
    environment:
      DATABASE_URL: "postgresql://example_user:example_password@postgres_db:5432/example_db"

volumes:
  postgres_data:
